config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]

  resources :happies, only: %i[index]
  resources :angries, only: %i[index]
  resources :normals, only: %i[index]
  resources :items, only: %i[index] do
    resource :happies, only: %i[create destroy]
    resource :angries, only: %i[create destroy]
    resource :normals, only: %i[create destroy]
  end
end

app/models/angry.rb
class Angry < Like
  belongs_to :user
  belongs_to :item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/happy.rb
class Happy < Like
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :happies, dependent: :destroy
  has_many :angries, dependent: :destroy
  has_many :normals, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :item_id }
  validates :user_id, presence: true, uniqueness: { scope: :type }
  validates :item_id, presence: true, uniqueness: { scope: :type }
end

app/models/normal.rb
class Normal < Like
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :happies, dependent: :destroy
  has_many :angries, dependent: :destroy
  has_many :normals, dependent: :destroy
  has_many :happy_items, through: :happies, source: :item
  has_many :normal_items, through: :normals, source: :item
  has_many :angry_items, through: :angries, source: :item

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  #一行にまとめる
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  def happy?(item)
    happy_items.include?(item)
  end

  def normal?(item)
    normal_items.include?(item)
  end

  def angry?(item)
    angry_items.include?(item)
  end
end

app/controllers/angries_controller.rb
class AngriesController < ApplicationController
  def index
    @items = current_user.angry_items
  end

  def create
    @item = Item.find(params[:item_id])
    current_user.angries.create!(item_id: @item.id)
		redirect_to items_path, success: '成功しました'
  end

  def destroy
    @item = Item.find(params[:item_id])
    angry = current_user.angries.find_by!(item_id: @item.id)
    angry.destroy!
		redirect_to items_path, success: '成功しました'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  def not_authenticated
    flash[:warning] = t('defaults.message.require_login')
    redirect_to login_path
	end
end

app/controllers/happies_controller.rb
class HappiesController < ApplicationController
  def index
    @items = current_user.happy_items
  end

  def create
    @item = Item.find(params[:item_id])
    current_user.happies.create!(item_id: @item.id)
    redirect_to items_path, success: '成功しました'
  end

  def destroy
    @item = Item.find(params[:item_id])
    @happy = current_user.happies.find_by!(item_id: @item.id)
    @happy.destroy!
    redirect_to items_path, success: '成功しました'
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    create_rakuten_data(params)
    @q = Item.ransack(params[:q])
    @items = @q.result.page(params[:page])
  end


  private
    def create_rakuten_data(params)
      @results = RakutenWebService::Ichiba::Item.search(
        keyword: '介護食',
        page: params[:page],
        hits: 30)

      @results.each do |result|
        item = Item.new(read(result))
        unless Item.all.exists?(name: item.name)
          item.save
        end
      end
    end

    def read(result)
      image= result['mediumImageUrls'][0]
      name = result['itemName']
      url = result['itemUrl']
      {
        image: image,
        name: name,
        url: url
      }
    end
end

app/controllers/normals_controller.rb
class NormalsController < ApplicationController
  def index
    @items = current_user.normal_items
  end

  def create
    @item = Item.find(params[:item_id])
    current_user.normals.create!(item_id: @item.id)
    redirect_to items_path, success: '成功しました'
  end

  def destroy
    @item = Item.find(params[:item_id])
    normal = current_user.normals.find_by!(item_id: @item.id)
    normal.destroy!
    redirect_to items_path, success: '成功しました'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def top
    @item = Item.first
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
			flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :require_login
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: t('.success')
    else
			flash.now[:danger] = t('.fail')
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
  def add_active_class(path)
    path = path.split('?').first
    'tab-active' if current_page?(path)
  end
end

app/views/angries/_like.html.erb
<%= turbo_frame_tag dom_id(item,:angry_like) do %>
  <%= button_to item_angries_path(item_id: item.id),class: "btn btn-info", method: :post do %>
    angry
  <% end %>
<% end %>

app/views/angries/_unlike.html.erb
<%= turbo_frame_tag dom_id(item,:angry_like) do %>
  <%= button_to item_angries_path(item_id: item.id),method: :delete do %>
    <%=image_tag 'obaba_angry.png', size: '150x150' %>
    Angry <%=item.angries.count%>
  <% end %>
<% end %>

app/views/angries/index.html.erb
<div class="mx-auto px-1 py-3 sm:px-1 max-w-3xl text-center">
  <h1>食べた感想は?</h1>
  <h1>Angry</h1>
  <br>
  <%= render 'shared/tab'%>
  <%= render partial: "items/item", collection: @items %>
</div>

app/views/happies/_like.html.erb
<%= turbo_frame_tag dom_id(item,:happy_like) do %>
  <%= button_to item_happies_path(item_id: item.id),class: "btn btn-warning", method: :post do %>
    happy
  <% end %>
<% end %>

app/views/happies/_unlike.html.erb
<%= turbo_frame_tag dom_id(item,:happy_like) do %>
  <%= button_to item_happies_path(item_id: item.id),method: :delete do %>
    <%=image_tag 'obaba_happy.png', size: '150x150' %>
    Happy <%=item.happies.count%>
  <% end %>
<% end %>

app/views/happies/create.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@item, :happy_like), partial: 'happies/unlike', locals: { item: @item }) %>

app/views/happies/destroy.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@item,:happy_like), partial: 'happies/like', locals: { item: @item }) %>

app/views/happies/index.html.erb
<div class="mx-auto px-1 py-3 sm:px-1 max-w-3xl text-center">
  <h1>食べた感想は?</h1>
  <h1>Happy</h1>
  <br>
  <%= render 'shared/tab'%>
  <%= render partial: "items/item", collection: @items %>
</div>

app/views/items/_item.html.erb
<div class="card w-96 bg-base-100 shadow-xl my-3">
  <%= image_tag  item.image ,size: "250x250", class: "mx-auto"%>

  <div class="card-body items-center text-center">
    <h2 class="card-title">
      <%= item.name %>
    </h2>
    <button class="btn btn-secondary">
      <%= link_to item.url do%>
        楽天市場へ
      <% end %>
    </button>
    <h5>食べた感想は?</h5>
    <%= render 'likes/likes', item: item %>
  </div>
</div>

app/views/items/_search.html.erb
<%= search_form_for q, html: { data: { turbo_frame: 'items-list' } } , url: url do |f|%>
  <div class="text-center my-3">
    <div class="my-2 font-weight-bold">キーワード検索</div>
    <%= f.search_field :name_cont %>
    <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
      検索
    <% end %>
  </div>
<% end %>

app/views/items/index.html.erb
<div class="mx-auto px-1 py-3 sm:px-1 max-w-3xl text-center">
  <%= render 'search', q: @q, url: items_path%>
  <%= render @items%>
  <%= paginate @items %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ObabameshiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico')%>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/likes/_likes.html.erb
<div class="flex">
  <% if current_user.happy?(item) %>
    <%= render 'happies/unlike', { item: item} %>
  <% elsif current_user.normal?(item)%>
    <%= render 'normals/unlike', { item: item} %>
  <% elsif current_user.angry?(item) %>
    <%= render 'angries/unlike', { item: item} %>
  <% else %>
    <%= render 'happies/like', { item: item} %>
    <%= render 'normals/like', { item: item} %>
    <%= render 'angries/like', { item: item} %>
  <% end %>
</div>

app/views/normals/_like.html.erb
<%= turbo_frame_tag dom_id(item,:normal_like) do %>
  <%= button_to item_normals_path(item_id: item.id),class: "btn btn-accent", method: :post do %>
    normal
  <% end %>
<% end %>

app/views/normals/_unlike.html.erb
<%= turbo_frame_tag dom_id(item,:normal_like) do %>
  <%= button_to item_normals_path(item_id: item.id), method: :delete do %>
    <%=image_tag 'obaba_normal.png', size: '150x150' %>
    Normal <%=item.normals.count%>
  <% end %>
<% end %>

app/views/normals/index.html.erb
<div class="mx-auto px-1 py-3 sm:px-1 max-w-3xl text-center">
  <h1>食べた感想は?</h1>
  <h1>Normal</h1>
  <br>
  <%= render 'shared/tab'%>
  <%= render partial: "items/item", collection: @items %>
</div>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="navbar bg-primary">
    <div class="navbar-start">
      <%=link_to  root_path, class: "btn btn-ghost flex" do%>
        OBABA MESHI
        <%=image_tag 'obaba_normal.png', size: '50x50' %>
      <% end %>
    </div>
    <div class="navbar-end">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-square btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </label>
        <ul tabindex="0" class="menu menu-conpact dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52 text-left">
          <li><%= link_to 'TOP', root_path %></li>
          <li><%= link_to '会員登録/ログイン', login_path %></li>
        </ul>
      </div>
    </div>
    <div class="navbar-end hidden lg:flex">
      <ul class="menu menu-horizontal p-0 mr-2">
        <li><%= link_to 'TOP', root_path %></li>
        <li><%= link_to '会員登録/ログイン', login_path %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert" id="error_messages">
    <% object.errors.full_messages.each do |message| %>
      <%= message%>
      <br>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="navbar bg-primary">
    <div class="navbar-start">
      <%=link_to  root_path, class: "btn btn-ghost flex" do%>
        OBABA MESHI
        <%=image_tag 'obaba_normal.png', size: '50x50' %>
      <% end %>
    </div>
    <div class="navbar-end">
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-square btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
        </label>
        <ul tabindex="0" class="menu menu-conpact dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52 text-left">
          <li><%= link_to 'TOP', root_path %></li>
          <li><%= link_to 'アイテム一覧', items_path %></li>
          <li><%= link_to '評価したアイテム一覧', happies_path %></li>
          <li>
            <%= button_to logout_path, method: :delete do %>
              Logout
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="navbar-end hidden lg:flex">
      <ul class="menu menu-horizontal p-0 mr-0 text-sm">
        <li><%= link_to 'TOP', root_path %></li>
        <li><%= link_to 'Logout', logout_path, class: 'dropdown-item', data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  </div>
</header>

app/views/shared/_tab.html.erb
<div class="tabs">
  <div class="<%= add_active_class(happies_path) %> tab tab-lg tab-lifted ">
    <%= link_to  happies_path do %>
      <%=image_tag 'obaba_happy.png', size: '70x70' %>
    <% end %>
  </div>
  <div class="<%= add_active_class(normals_path) %> tab tab-lg tab-lifted">
    <%= link_to normals_path do %>
      <%=image_tag 'obaba_normal.png', size: '70x70' %>
    <% end %>
  </div>
  <div class="<%= add_active_class(angries_path) %> tab tab-lg tab-lifted">
    <%= link_to angries_path do %>
      <%=image_tag 'obaba_angry.png', size: '70x70' %>
    <% end %>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="mx-auto px-1 py-3 sm:px-1 max-w-3xl text-center">
  <h1 class="font-bold text-4xl text-red-500">
    OBABA MESHI
  </h1>
  <p>介護食評価サイトです</p>
  <%= link_to 'obaba meshiへ', items_path, class: 'button btn btn-secondary'%>
  <div class="card w-96 bg-base-100 shadow-xl my-3">
    <%= image_tag  @item.image ,size: "250x250", class: "mx-auto"%>
    <div class="card-body items-center text-center">
      <h2 class="card-title">
        <%= @item.name %>
      </h2>
      <button class="btn btn-secondary">
        <%= link_to @item.url do%>
          楽天市場へ
        <% end %>
      </button>
      <h5>食べた感想は?</h5>
      <div class="flex">
        <%= button_to "#", class: "btn btn-warning", method: :post do %>
        happy
        <% end %>
        <%= button_to "#", class: "btn btn-accent", method: :post do %>
        normal
        <% end %>
        <%= button_to "#", class: "btn btn-info", method: :post do %>
        angry
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div class="container">
  <h1>ログイン</h1>
  <%= form_with url: login_path, local: true do |f| %>
    <div class="form-group">
      <%=f.label :email,User.human_attribute_name(:email) %><br>
      <%=f.email_field :email , class: 'form-control'%>
    </div>
    <div class="form-group">
      <%=f.label :password ,User.human_attribute_name(:password)%><br>
      <%=f.password_field :password, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit 'ログイン', class: 'btn btn-primary' %>
      <%= link_to '新規登録' ,new_user_path , class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div>
  <h1><%=  t '.title'  %></h1>
  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit (t '.title') , class: 'btn btn-primary my-2' %>
  <% end %>
</div>